// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/suhanyujie/workUser/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: WorkUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/find",
				Handler: UserFindHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: UserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/delete",
				Handler: UserDeleteHandler(serverCtx),
			},
		},
	)
}
