// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"github.com/suhanyujie/workUser/service/workUser/cmd/rpc/user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	CreateUserResp = user.CreateUserResp
	CreateUserReq  = user.CreateUserReq

	User interface {
		Create(ctx context.Context, in *CreateUserReq) (*CreateUserResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Create(ctx context.Context, in *CreateUserReq) (*CreateUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Create(ctx, in)
}
